apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081